title: durlav kalita
email: durlavk98@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hi, I am Durlav. Developer and chess enthusiast.
baseurl: "" # the subpath of your site, e.g. /blog
url: "durlavkalita.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: durlavk98
github_username:  durlavkalita

paginate: 5
paginate_path: "/blog/page:num/"

# Build settings
# theme: minima
remote_theme: pages-themes/hacker@v0.2.0

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-remote-theme

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "durlavk"
  - scope:
      path: ""
    values:
      layout: "default"
  